// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseDot: typeof import('./src/components/base/BaseDot.vue')['default']
    BaseEcharts: typeof import('./src/components/business/base-echarts/BaseEcharts.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseIconButton: typeof import('./src/components/base/BaseIconButton.vue')['default']
    BaseIconTip: typeof import('./src/components/base/BaseIconTip.vue')['default']
    BaseSearchButton: typeof import('./src/components/base/BaseSearchButton.vue')['default']
    IconEpDelete: typeof import('~icons/ep/delete')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    IconPreview: typeof import('./src/components/business/iconPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TySearchForm: typeof import('./src/components/business/TySearchForm.vue')['default']
    TyTable: typeof import('./src/components/business/TyTable.vue')['default']
  }
}
