version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_app_docker_compose
    ports:
      - '8081:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
